services:
  proxy:
    image: ubuntu/squid
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./squid.passwords:/etc/squid/passwords
    restart: always
