services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDB
    restart: always
    environment:
      TZ: Asia/Bangkok
      MARIADB_ROOT_PASSWORD: ''
      MARIADB_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb_logs:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro

  phpmyadmin:
    container_name: phpMyAdmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "80:80"
    environment:
      PMA_HOST: mariadb

volumes:
  mariadb_data:
  mariadb_logs:
